name: TruffleHog Secrets Scan
on: [workflow_dispatch]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          # Repository path
          path: ./
          # Start scanning from here (usually main branch).
          #base: ${{ github.event.repository.default_branch }}
          base: ${{ github.event.repository.repository }}
          # Scan commits until here (usually dev branch).
          # head: # optional
          # Extra args to be passed to the trufflehog cli.
          extra_args: --debug --only-verified
